name: sqlserver

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    ports:
      - "${SQLSERVER_PORT}:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
      - ./backup:/var/opt/mssql/backup

volumes:
  sqlserverdata:
